### ISSUE TITLE
All devices cannot see Alerter’s location -- on the alert itself as well as the map screen the error "Emergency alert signal could not be pinpointed on a map" appears. 

### ISSUE THREAD

**Issue by TechForJustice** [betterangels/better-angels#133]
Steps to reproduce: Login to www.techforjustice.org/wp-admin > Tap Activate alert > The Screen now says “Emergency alert signal could not be pinpointed on map.” I checked my phone and the location settings are on, checked google chrome and the settings say that it will ask permission first so it's on too.

**Comment by TechForJustice** [comment]
This error message also appears even when the Alerter's location is detected and shows up on the map.
![picture1](https://cloud.githubusercontent.com/assets/11147797/12969543/ab7e0cb6-d047-11e5-931e-dcf25e878211.png)

**Comment by meitar** [comment]
> This error message also appears even when the Alerter's location is detected and shows up on the map.

The error depicted here is in reference to the *incident location*, not a responder's current location. It means that at the time the alert button was pressed, we could not detect a GPS location. This can happen for a number of reasons, including with Location services on, because it might take longer to get GPS coordinates than we are willing to wait. (We wait a hardcoded 5 seconds maximum for now.)

I think the UX here needs serious work, but this issue is a bit confused and confusing. Since we're reorganizing the repository generally anyway, I'm gonna close this one out for now.
