### ISSUE TITLE
Can we add user-generated offline geolocation navigation?

### ISSUE THREAD

**Issue by hannahhubbard** [betterangels/better-angels#62]
Google offers offline mapping and tracking.

http://techcrunch.com/2015/11/10/offline-navigation-comes-to-google-maps/

Would it be possible to allow both service providers (legal aid, shelters, advocacy groups, etc) and end users to collectively add maps so users who lose internet connection or are without connection will also be able to use Buoy location tracker?

**Comment by meitar** [comment]
See also #18 for custom map data.

Should look into whether HTML5 LocalStorage can be used for any of the Web mapping APIs (Google Maps, OpenStreetMap, others?).

**Comment by meitar** [comment]
Did a bit of research on using the [HTML5 LocalStorage APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) for this issue and it looks like it's a violation of Google Maps's Terms of Use to cache tiles offline. (The Google Maps app itself is allowed to do this because it is made by Google.) However, [OpenStreetMaps (OSM) not only makes offline use possible, but encourages the offline use case](https://wiki.openstreetmap.org/wiki/Offline_Openstreetmap).

Also, I've received some feedback from people in the free software community indicating that they would be more comfortable if Buoy switched to using OSM instead of GMaps as a mapping service (for obvious reasons). For that reason and others, I think it would be valuable for us to switch to using OSM as soon as possible (as indicated in #18 as well).

Finally, @hannahhubbard, can you say more about what you mean by "user-generated" in this context? I don't think I understand what you're getting at when you say that.

**Comment by meitar** [comment]
This issue has been migrated to betterangels/buoy#17.
