### ISSUE TITLE
Uploaded media cannot be sent (is not visible) to responders in chat room

### ISSUE THREAD

**Issue by roseline1** [betterangels/better-angels#92]
Any media uploaded only appears in the drop-down menu under its specified file category. There is no option available to send the media or post the media to be visible to team members in a chat room.
Once an uploaded file is selected, a new computer tab opens to display a larger view of the file but no further action is carried out after that.

**Comment by meitar** [comment]
Thanks for adding this.

More precisely, the video is visible only to responders who arrive at the incident chat after the media has been shared; we need to refactor the web client so that when it polls for new info it also retrieves any new media attachments, not only retrieving new location updates.

This part:

> Once an uploaded file is selected, a new computer tab opens to display a larger view of the file but no further action is carried out after that.

…is a bug described by #87.

**Comment by meitar** [comment]
This issue has been migrated to betterangels/buoy#38.
